services:
  backend:
    image: 24802117/network-panel:latest
    container_name: network-panel
    restart: unless-stopped
    environment:
      DB_HOST: ip
      DB_NAME: panel
      DB_USER: root
      DB_PASSWORD: 123456
      JWT_SECRET: network-panel-secret-yjkj02
      LOG_DIR: /app/logs
    ports:
      - "6365:6365"
    volumes:
      - ./backend_logs:/app/logs
    healthcheck:
      test: ["CMD", "sh", "-c", "wget --no-verbose --tries=1 --spider http://localhost:6365/flow/test || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s